macro(compile_batch __sources)
    foreach(__source ${__sources})
        get_filename_component(__exec ${__source} NAME_WE)
        add_executable(${__exec} ${__source})
        if(${ARGC} GREATER "1") 
            target_link_libraries(${__exec} ${ARGN})
        endif()
    endforeach()
endmacro()
